train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-clean-360"
  instance_transforms: ${transforms.instance_transforms.train}
  max_audio_length: 20.0
  max_text_length: 200
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  max_audio_length: 20.0
  max_text_length: 200
  limit: 50
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
  max_audio_length: 20.0
  max_text_length: 200
  limit: 50
