train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-other-500"
  instance_transforms: ${transforms.instance_transforms.train}
  max_audio_length: 20.0
  max_text_length: 200
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-other"
  max_audio_length: 20.0
  max_text_length: 200
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-other"
  instance_transforms: ${transforms.instance_transforms.inference}
