defaults:
  - model: main
  - writer: wandb
  - metrics: train1
  - datasets: test
  - dataloader: train1
  - transforms: train1
  - _self_

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  lm: 3-gram.arpa
  vocab: librispeech-vocab.txt

inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "inference" # any name here, can be a dataset name
  seed: 1
  override: True
  from_pretrained: "model_best_3.pth" # path to the pretrained model
