train:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  audio:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
        p: 0.05
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.ColoredNoise
        p: 0.05
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.Shift
        p: 0.05
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.PitchShift
        p: 0.05
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.BandPassFilter
        min_center_frequency: 300
        max_center_frequency: 4000
        min_bandwidth_fraction: 1.5
        p: 0.05
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.BandStopFilter
        p: 0.05
        max_bandwidth_fraction: 1.5
        min_center_frequency: 1500
        max_center_frequency: 2500
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.HighPassFilter
        p: 0.05
        max_cutoff_freq: 1000
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.LowPassFilter
        p: 0.05
        min_cutoff_freq: 1000
        sample_rate: 16000


  spectrogram:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.spec_augs.FrequencyMasking
        freq_mask_param: 40
        p: 0.1
      - _target_: src.transforms.spec_augs.TimeMasking
        time_mask_param: 40
        p: 0.1

inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
