train:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  audio:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
        p: 0.2
      - _target_: src.transforms.wav_augs.ColoredNoise
        p: 0.3
        sample_rate: 32
      - _target_: src.transforms.wav_augs.BackGroundNoise
        p: 0.2
      - _target_: src.transforms.wav_augs.Shift
        p: 0.3
      - _target_: src.transforms.wav_augs.PitchShift
        p: 0.2
      - _target_: src.transforms.wav_augs.BandPassFilter
        p: 0.1
        low_freq: 50
        high_freq: 2000
      - _target_: src.transforms.wav_augs.BandStopFilter
        p: 0.1
        low_freq: 50
        high_freq: 2000
      - _target_: src.transforms.wav_augs.HighPassFilter
        p: 0.1
        cutoff_freq: 500
      - _target_: src.transforms.wav_augs.LowPassFilter
        p: 0.1
        cutoff_freq: 2000

  spectrogram:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.spec_augs.FrequencyMasking
        freq_mask_param: 40
        p: 0.2
      - _target_: src.transforms.spec_augs.TimeMasking
        time_mask_param: 40
        p: 0.2
      - _target_: src.transforms.spec_augs.TimeStretch
        time_mask_param: 40
        p: 0.2

inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
